### ISSUE TITLE
move WaNo Files to top level of the project

### ISSUE THREAD

**Issue by schaarj** [KIT-Workflows/DFT-VASP#1]
according to the current roadmap, WaNos should be incorporable to SimStack by cloning the repository inside the SimStack Nano path

```bash
git clone https://github.com/KIT-Workflows/DFT_VASP.git DFT_VASP
```
However for this to work the important files (xml and yml) need to be in top level of the project.

**Comment by Celso0408** [comment]
Okay, I'll change it!
